### ISSUE TITLE
要素の重なり順序がおかしい？

### ISSUE THREAD

**Issue by napo0703** [napo0703/WakaruLand#54]
FireFoxで投稿画面が動きません。
Safari,Chromeでも動かなくなる時があります。
ボタンや画像は表示されているけどクリックできない/ドラッグで選択できないので、クリックイベント等が下のレイヤに伝播してないからだと推測しています。
z-indexとかだと思うのですが…

**Comment by napo0703** [comment]
これですね
http://heartbrain.net/blog150610

**Comment by ghost** [comment]
今日のIDPの件で、僕もflexboxを見直してたのですが、
今書いているfloat,marginやpositionやらをなくして
下記だけで意図しているようにはなるはずです。

``` css
#wrapper {
    display: flex;
}
#console {
    width: 400px; /*固定したい幅の長さ*/
}
#grid {
    flex: 1;
}
```

**Comment by napo0703** [comment]
できました！
`display: flex;` 知らなかったです。ありがとうございます。

**Comment by ghost** [comment]
ちなみに、grid_viewの部分もfloatとか使わずにdisplay flexで解決できるはずです。
jsでresizeイベント取ってstyle当ててるみたいなので、がっつり確認はしてませんが、

``` css
(親div)
.grid_view {
   display: flex;
   -webkit-flex-flow: row wrap; /*vender prefixは良きようにしてください*/
   justify-content: space-around; /*又は、flex-startで子にmarginつけるとか*/
}
(子)
.cell {
  width: 〇〇; /*任意の幅 %指定の方が良いかも*/
}
```

多分こんな感じでいけるはずです。調べたりして良ければ使ってみてください。
